### PR TITLE
Added memory bandwidth performance counters in sparse adagrad kernel

### PR DESCRIPTION
**Pull request by ishwarbhati**
@ddkalamk please review and merge

### CODE REVIEW

**Comment by hfp** [comment]
( Hmm, it looks like this PR is overriding the revised Makefile. This can be intentional, but perhaps also result from just not resolving conflicts. )

**Comment by ishwarbhati** [comment]
I used the latest Makefile @ddkalamk  was using for this kernel, overrode the earlier one.

**Comment by alheinecke** [comment]
@ddkalamk was outdated, can you please use the latest makefile and merge it with the changes of @ddkalamk ?

**Comment by ishwarbhati** [comment]
I reverted Makefile to use the revised version.

**Review by alheinecke — COMMENTED** [review]
can you please use libxsmm_aligned_malloc/libxsmm_free instead of _mm_malloc hoisted through my_malloc?

**Comment by ishwarbhati** [comment]
done --added libxsmm malloc/free

**Review by alheinecke — COMMENTED** [review]
can you please get rig of _mm_malloc completely there is issues with compilers other than ICC. Just use libxsmm_aligned_malloc in all cases.

**Comment by ibhati** [comment]
@alheinecke I removed _mm_malloc calls completely. Please review again. thanks

**Comment by ddkalamk** [comment]
Looks good to me...

**Comment by hfp** [comment]
Thank you!  I will merge asap.

**Pull request merged**
