### PR TITLE
Fixed run_deepbench.sh to run only libxsmm format

### PR DESCRIPTION
**Pull request by dmudiger**

### CODE REVIEW

**Comment by alheinecke** [comment]
Can we add a new script which only runs "A L", right now the script doesn't support the other formats anymore, but within a couple of we will have a performance fix (c.f. #137)

**Comment by dmudiger** [comment]
For DeepBench we would want only the best performing variant. I can modify the script to take the format as an argument.

**Comment by alheinecke** [comment]
That would be great, perhaps we should also add the last parameter to toggle logical vs, physical padding?!

**Comment by alheinecke** [comment]
thanks and merged.

**Comment by dmudiger** [comment]
done, updated run script with additional arguments.

**Pull request merged**
