### PR TITLE
Avoid reloads in libxsmm_spmdm_compute_fp32_thread.

### PR DESCRIPTION
**Pull request by legrosbuffle**
Because of aliasing, the compiler cannot prove that `handle->n` and
`handle->m` do not change. It has to reload them at every loop
iteration, wasting a significant time.

We have measured an improvement of 0-5% (median 1.6%) on our internal tensorflow
sparse matrix multiplication benchmarks.

### CODE REVIEW

**Comment by hfp** [comment]
Thank you very much for your contribution!

**Comment by hfp** [comment]
As you seem to be still interested in LIBXSMM's functionality (at least SPMDM), have you noticed this desaster: [https://github.com/tensorflow/tensorflow/pull/24706](https://github.com/tensorflow/tensorflow/pull/24706)?

I was urged to help adjusting things for an API change in TF (allocator stuff), then nobody looked at the PR for a long time, and finally I was asked to reformat the files. Of course, I would write new code adhering to any required (format-)policy. However, this was completely unrelated work.

Anyhow, the PR cotained the following:
1. Necessary fix to deal with TF's change to the allocation API. Mostly some cleanup as the change was on Xsmm's side to accomodate the revised TF API.
2. Updated code for integrating Xsmm's convolutions to at least work (again).
3. Enabled Xsmm's BFloat support for SpMDM.

Regarding the latter (3), Bfloat for SpMDM was always present since the first integration between TF and XSMM. However, at that time (TF v1.1) TensorFlow had no (public) support for Bf16 (likely because of no foundation in Eigen, etc.). My recommendatation would be to look at enabling Xsmm/Bf16 in TF.

Regarding (2), I think integration of convolution is outdated and can be removed. Main reason is that today, one would likey integrate Xsmm into Eigen and then leverage this work in TF. See also a placeholder about such work: https://github.com/hfp/libxsmm/issues/281. This is also true because both TF and Xsmm progressed for instance wrt code fusion.

Our next release of Xsmm (1.14) will contain your PR. Our upcoming v2.0 merge a completely revised DL implementation based on a universal batch-reduce kernel which comes with extensive support for low precision, future instruction set extensions, and combined layers as well as entirely new layer kinds.

**Comment by legrosbuffle** [comment]
Hi Hans,

I'm working on global performance, not TensorFlow specifically, so I do not know the exactly how the TF team handles pull requests. That being said I had a quick look at your pull request, and there did not seem to be any pending issue, so I'm wondering why it has not been merged. I'll ping  the TF team.

**Comment by jewillco** [comment]
Will this change be in a release? That makes it easier to pull in for
TensorFlow.

-- Jeremiah Willcock

**Comment by legrosbuffle** [comment]
@jewillco : according to @hfp's comment, it will be in 1.14.

> Our next release of Xsmm (1.14) will contain your PR.

**Comment by hfp** [comment]
This PR #355 is part [LIBXSMM v1.14](https://github.com/hfp/libxsmm/releases/tag/1.14)!

In addition, I have validated [v1.14](https://github.com/hfp/libxsmm/releases/tag/1.14) against TF/master. For latter, I have locally updated https://github.com/tensorflow/tensorflow/pull/24706 to TF/master (as of 25th Oct. 2019) and [compiled](https://libxsmm.readthedocs.io/tensorflow/) with LIBXSMM (`--define tensorflow_xsmm_convolutions=1 --define tensorflow_xsmm_backward_convolutions=1 --define tensorflow_xsmm=1`). I have tested in particular SpMDM:

```
bazel-bin/tensorflow/core/kernels/sparse_matmul_op_test --benchmarks=all
bazel-bin/tensorflow/core/kernels/sparse_matmul_op_test
```

Updating https://github.com/tensorflow/tensorflow/pull/24706 to current TF/master was straight-forward.

**Pull request merged**
