### PR TITLE
Groupnorm Code

### PR DESCRIPTION
**Pull request by narendrachaudhary51**
I have added the groupnorm code in samples/equation/equation_groupnorm.c file.
It have followed a design that is similar to equation_layernorm.c file. 
Groupnorm code is working for FP32 and BF16 precision according to my testing. You can also test the code by using a command line. I have not removed some of the layernorm code because I use it to test BF16 implementation.

### CODE REVIEW

**Review by alheinecke — CHANGES_REQUESTED** [review]
I don't think it makes sense to touch the conv1dopti in this PR. Why is that needed?

**Comment by narendrachaudhary51** [comment]
@alheinecke I was using the using the older branch and pushed changes from it. I only corrected a one line change in conv1dopti layer example code (making ms time unit to sec). Do you want to revert that change and resubmit it separately? Or do you want me to create a separate branch for Groupnorm?

**Comment by alheinecke** [comment]
OK, then it's fine if you are saying that this is bugfix. Ideally, we should just do 2 PRs, but if you are fine with one, I will just merge.

**Comment by narendrachaudhary51** [comment]
@alheinecke I fine with it for now. Next time, I will create a different PR.

**Pull request merged**
