### PR TITLE
modified check for pad  applicable to googlenet v3

### PR DESCRIPTION
**Pull request by taknevski**

### CODE REVIEW

**Comment by alheinecke** [comment]
Can you please also submit it a script which tests Googlenetv3 convolutions in samples/dnn

**Comment by taknevski** [comment]
Hi Alex,

I can do that, but the reproduced needs an additional field for pad_w
because pad_w may not equal pad_h in googlenet v3

Regards,
Anand

**Comment by hfp** [comment]
Hello Anand,

perhaps  e5bac4b will help to get a distinct `pad_w`; feel free to adjust until it suits the requirement.

Hans

**Comment by alheinecke** [comment]
I think the problem is that we need pad cmd parameter in H and in W direction. So we need to change all the scripts etc. However, this is what needs to be done. 
Today we have:
./layer_example_f32 iters inpWidth inpHeight nImg nIfm nOfm kw kh pad stride type format padding_mode
and we need:
./layer_example_f32 iters inpWidth inpHeight nImg nIfm nOfm kw kh padw padh stride type format padding_mode
For all our current scripts: padw=padh

**Comment by taknevski** [comment]
yes you need an addiitonal parameter for pad_w..

**Comment by alheinecke** [comment]
Can you please include the driver changes for fp32, int16, int8 and the modification of all other scripts into this PR?

Thanks!

**Comment by hfp** [comment]
How to proceed with this PR, is there some more work pending?

**Pull request merged**
