### PR TITLE
fix cut and sed issues on Mac plus spellcheck

### PR DESCRIPTION
**Pull request by jeffhammond**
1) i fixed two spelling errors in comments because i am OCD about grammar (but not capitalization, as you can see)
2) Mac (and other non-Linux systems) have lame cut/sed that do not like some of the options used.  make them work on Mac with non-standard cut and modification to sed invocation.

### CODE REVIEW

**Comment by alheinecke** [comment]
can you please the latest commit, your commit was broken on linux

**Comment by jeffhammond** [comment]
Ok. I didn't test on Linux. I assumed you'd do that before accepting pull request :-)

**Comment by jeffhammond** [comment]
I do not see any issue on my Linux machine.  The following command completes successfully.
```
make ROW_MAJOR=1 AVX=2 M="$(echo $(seq 2 2 8))" N="$(echo $(seq 2 2 8))" K="$(echo $(seq 2 2 8))" all test
```

**Comment by alheinecke** [comment]
Yeah, I fixed linux using mktemp, can you please re-test MAC?

**Comment by jeffhammond** [comment]
```
jrhammon-mac01:libxsmm jrhammon$ make CUT=/usr/local/Cellar/coreutils/8.24/libexec/gnubin/cut ROW_MAJOR=1 AVX=2 M="$(echo $(seq 8 8 32))" N="$(echo $(seq 8 8 16))" K="$(echo $(seq 8 8 16))" all test
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
make: *** [include/libxsmm.f90] Error 1
```

:-(

**Comment by jeffhammond** [comment]
I see there is a mktemp in the same place as the coreutils cut that I needed.  Let me try that.

**Comment by jeffhammond** [comment]
So I can workaround this by doing a dry-run with Make (`... -n >& jeff.sh ; ./jeff.sh`, where `jeff.sh` has `!/bin/bash -x` at the top) until it dies here:
```
mkdir -p lib/intel64/
xiar -rs lib/intel64/libxsmm.a build/intel64/mm_8_8_8.o build/intel64/mm_8_8_16.o build/intel64/mm_8_16_8.o build/intel64/mm_8_16_16.o build/intel64/mm_16_8_8.o build/intel64/mm_16_8_16.o build/intel64/mm_16_16_8.o build/intel64/mm_16_16_16.o build/intel64/mm_24_8_8.o build/intel64/mm_24_8_16.o build/intel64/mm_24_16_8.o build/intel64/mm_24_16_16.o build/intel64/mm_32_8_8.o build/intel64/mm_32_8_16.o build/intel64/mm_32_16_8.o build/intel64/mm_32_16_16.o build/intel64/libxsmm.o
cd /Users/jrhammon/Work/INTEL/MKL/libxsmm/samples/smm && /Applications/Xcode.app/Contents/Developer/usr/bin/make SYM=0 DBG=0 IPO=0
make[1]: *** No rule to make target `../../lib/intel64/libxsmm.so', needed by `smm'.  Stop.
```

On Mac, I have only static libraries (not generally, but in this case)...

**Comment by alheinecke** [comment]
That's strange. Have you done make realclean before. *.so are just built if STATIC=0 is set when calling make. Both calls work for me under Linux:

make realclean
make MNK="8"

make realclean
# this is needed to run the generator during make
export LD_LIBRARY_PATH=./lib/intel64:$LD_LIBRARY_PATH 
make MNK="8" STATIC=0

**Comment by jeffhammond** [comment]
I recall doing "make realclean" before every build attempt, but I will try
STATIC option.

On Thu, Oct 8, 2015 at 7:41 AM, Alexander Heinecke <notifications@github.com
> wrote:

> That's strange. Have you done make realclean before. *.so are just built
> if STATIC=0 is set when calling make. Both calls work for me under Linux:
>
> make realclean
> make MNK="8"
>
> make realclean
> this is needed to run the generator during make
>
> export LD_LIBRARY_PATH=./lib/intel64:$LD_LIBRARY_PATH
> make MNK="8" STATIC=0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hfp/libxsmm/pull/10#issuecomment-146566614>.
>



-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Pull request merged**
