### PR TITLE
Improve perf support

### PR DESCRIPTION
**Pull request by mdebski**
This modifies and cleans up perf support a bit, with biggest change being including BSD-3 jitdump.h replacement I've implemented basing on format documentation by Stephane Eranian (Thanks!).

### CODE REVIEW

**Comment by mdebski** [comment]
I haven't tested this on anything else than linux.

**Comment by alheinecke** [comment]
The travis test discovered some issues, can you please have look?
Thanks!

**Comment by hfp** [comment]
I have taken the PR; see f9bf527 for the adjustments (perhaps one may read the commit log). Please verify and readjust as necessary.

**Comment by mdebski** [comment]
Thanks! I've already finished my internship, but could have done it if not for the fact I've been in Mexico for last 2 weeks, without my laptop. Thanks for handling this!

**Pull request merged**
