### PR TITLE
Unary and Gelu Commit: Part1

### PR DESCRIPTION
**Pull request by deeptiag1**
Unary Exp is fully validated

### CODE REVIEW

**Comment by deeptiag1** [comment]
@alheinecke: Ported Comments from Part522: This function is not load a vector of constants. It's broadcasting a constant scalar. I like that function, however, relu and dropout need such a thing as well so it would be great to back port there as well. At least it should be renamed to what it's doing.
I'm not convinced this is the right semantics what we need for some of the usages (where we really need to load a vector)... e.g. in GeLU

**Comment by alheinecke** [comment]
do you want me to do review/merge or should I wait until the load broadcast routine is moved ?

**Comment by deeptiag1** [comment]
Fixing the load broadcast routine. Checking the requirements in Gelu and Relu to sync in one shot

**Comment by alheinecke** [comment]
do you have some updates on the load broadcast routine (moving to the correct file, and renaming?)

**Pull request merged**
